version: 0.1.0.{build}
image: Visual Studio 2019
configuration: Release
platform: x64

environment:
  URL_1CV8T:
    secure: z47uplaqZaQ0ZkroXy0GP00nv6ACPwovtb+EjfPgpS1UVp1iZSkRJGz8uOWarUXi

build_script:
  - ps: if (!(Test-Path 1cv8t.7z)) { Invoke-WebRequest -Uri $env:URL_1CV8T -OutFile 1cv8t.7z }
  - 7z x 1cv8t.7z
  - mkdir database
  - bin\1cv8t.exe CREATEINFOBASE File=%CD%/database
  - bin\1cv8t.exe DESIGNER /F %CD%/database /LoadExternalDataProcessorOrReportFromFiles AFViewer.xml AFViewer.epf /Out AFViewer.log
  - 7z a inetpub.zip inetpub

cache:
  - 1cv8t.7z

artifacts:
  - path: AFViewer.epf
  - path: AFViewer.log
  - path: inetpub.zip

deploy:
  - provider: GitHub
    auth_token:
      secure: v7P89NQ2I5+WGNNdhpFrZEt6OCTPf8A8VSC5rttZMXh3DJ2fTChNEjZ1Wvm3kfBt
    repository: lintest/AFViewer1C
    artifact: AFViewer.epf, inetpub.zip
    draft: true
    prerelease: true
    force_update: true
    on:
      branch: master
